### ISSUE TITLE
Any android sample how to send APDU to BLE Smartcard reader please.

### ISSUE THREAD

**Issue by mouthdog** [fidesmo/apdu-over-ble#17]
Do you have any sample, how to send APDU command to BLE Smartcard reader? I try to do an android application to scan the BLE device and connected it to read all UUID service. But I don't know how to send APDU to collect data from the smartcard. Welcome your comment.

**Comment by martinpaljak** [comment]
You need to talk the BLE protocol defined by  the BLE smart card reader. For that, please contact your smart card reader vendor for docs and references.
