### ISSUE TITLE
Max memory for APDU processing description error

### ISSUE THREAD

**Issue by sergkh** [fidesmo/apdu-over-ble#9]
We have a description issue [here](https://github.com/fidesmo/apdu-over-ble/blob/master/spec/apdu-service-spec.md#characteristic-max-memory-for-apdu-processing). Where we first say that memory is set in kilobytes, while later in the payload specification specifying it as `Payload: memory (in bytes)`.

I suppose the correct one is in bytes, as kilobytes will give very rough estimation (and we generally do not much care if memory limit is very big).

WDYT @miguelcardo ?

**Comment by miguelcardo** [comment]
They are two different things, but I am OK with using the same units for both quantities. Feel free to express the max memory for APDU processing using `bytes` as well.
